# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

general {
    col.active_border = rgba(3d5355ff) 
    col.inactive_border = rgb(101315)
    gaps_in = 4
    gaps_out = 8
    border_size = 2
}

group {
    col.border_active = $activeBorderColor
}
